METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 20]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  model_args:
    num_nodes: 207
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    lstm_hidden_dim: 64
    num_layers: 3
    seq2seq: True

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 20]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  model_args:
    num_nodes: 325
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    lstm_hidden_dim: 64
    num_layers: 3
    seq2seq: True

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 20]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  model_args:
    num_nodes: 358
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    lstm_hidden_dim: 64
    num_layers: 3
    seq2seq: True

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 20]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  model_args:
    num_nodes: 307
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    lstm_hidden_dim: 64
    num_layers: 3
    seq2seq: True

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 20]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  model_args:
    num_nodes: 883
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    lstm_hidden_dim: 64
    num_layers: 3
    seq2seq: True

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 20]
  clip_grad: 0
  batch_size: 64
  max_epochs: 300

  model_args:
    num_nodes: 170
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    lstm_hidden_dim: 64
    num_layers: 3
    seq2seq: True
    