METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [80]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 207
    in_dim: 2
    seq_length: 12
    out_dim: 12
    device: null # will be updated
    gcn_true: True
    buildA_true: True
    gcn_depth: 2
    predefined_A: null
    static_feat: null
    dropout: 0.3
    subgraph_size: 20 # topk
    node_dim: 40
    dilation_exponential: 1
    conv_channels: 32
    residual_channels: 32
    skip_channels: 64
    end_channels: 128
    layers: 3
    propalpha: 0.05
    tanhalpha: 3
    layer_norm_affline: True

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [50]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 325
    in_dim: 2
    seq_length: 12
    out_dim: 12
    device: null # will be updated
    gcn_true: True
    buildA_true: True
    gcn_depth: 2
    predefined_A: null
    static_feat: null
    dropout: 0.3
    subgraph_size: 20 # topk
    node_dim: 40
    dilation_exponential: 1
    conv_channels: 32
    residual_channels: 32
    skip_channels: 64
    end_channels: 128
    layers: 3
    propalpha: 0.05
    tanhalpha: 3
    layer_norm_affline: True

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  time_of_day: True

  train_size: 0.6
  val_size: 0.2
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [115]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 358
    in_dim: 2
    seq_length: 12
    out_dim: 12
    device: null # will be updated
    gcn_true: True
    buildA_true: True
    gcn_depth: 2
    predefined_A: null
    static_feat: null
    dropout: 0.3
    subgraph_size: 20 # topk
    node_dim: 40
    dilation_exponential: 1
    conv_channels: 32
    residual_channels: 32
    skip_channels: 64
    end_channels: 128
    layers: 3
    propalpha: 0.05
    tanhalpha: 3
    layer_norm_affline: True

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  time_of_day: True

  train_size: 0.6
  val_size: 0.2
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [175]
  early_stop: 15
  clip_grad: 5
  batch_size: 64
  max_epochs: 500
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 307
    in_dim: 2
    seq_length: 12
    out_dim: 12
    device: null # will be updated
    gcn_true: True
    buildA_true: True
    gcn_depth: 2
    predefined_A: null
    static_feat: null
    dropout: 0.3
    subgraph_size: 20 # topk
    node_dim: 40
    dilation_exponential: 1
    conv_channels: 32
    residual_channels: 32
    skip_channels: 64
    end_channels: 128
    layers: 3
    propalpha: 0.05
    tanhalpha: 3
    layer_norm_affline: True

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  time_of_day: True

  train_size: 0.6
  val_size: 0.2
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [108]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 883
    in_dim: 2
    seq_length: 12
    out_dim: 12
    device: null # will be updated
    gcn_true: True
    buildA_true: True
    gcn_depth: 2
    predefined_A: null
    static_feat: null
    dropout: 0.3
    subgraph_size: 20 # topk
    node_dim: 40
    dilation_exponential: 1
    conv_channels: 32
    residual_channels: 32
    skip_channels: 64
    end_channels: 128
    layers: 3
    propalpha: 0.05
    tanhalpha: 3
    layer_norm_affline: True

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  time_of_day: True

  train_size: 0.6
  val_size: 0.2
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [168]
  early_stop: 15
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 170
    in_dim: 2
    seq_length: 12
    out_dim: 12
    device: null # will be updated
    gcn_true: True
    buildA_true: True
    gcn_depth: 2
    predefined_A: null
    static_feat: null
    dropout: 0.3
    subgraph_size: 20 # topk
    node_dim: 40
    dilation_exponential: 1
    conv_channels: 32
    residual_channels: 32
    skip_channels: 64
    end_channels: 128
    layers: 3
    propalpha: 0.05
    tanhalpha: 3
    layer_norm_affline: True
    