METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0
  milestones: [10, 30]
  # milestones: [80]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: False
  cl_step_size: 2500

  pass_device: True

  model_args:
    num_nodes: 207
    node_emb_file: "../data/METRLA/spatial_embeddings.npz"
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    model_dim: 32
    tod_embedding_dim: 24
    dow_embedding_dim: 7
    node_embedding_dim: 64
    z_dim: 32
    learner_hidden_dim: 64
    feed_forward_dim: 64
    num_heads: 4
    num_layers: 1
    dropout: 0
    with_spatial: True

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0001
  milestones: [10, 40]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: False
  
  pass_device: True

  model_args:
    num_nodes: 325
    node_emb_file: "../data/PEMSBAY/spatial_embeddings.npz"
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    model_dim: 32
    tod_embedding_dim: 24
    dow_embedding_dim: 7
    node_embedding_dim: 64
    z_dim: 32
    learner_hidden_dim: 128
    feed_forward_dim: 128
    num_heads: 4
    num_layers: 1
    dropout: 0.1
    with_spatial: True
  